### ISSUE TITLE
GLCMTextures in Python

### ISSUE THREAD

**Issue by henzb72** [ailich/GLCMTextures#22]
Hi Ailich,

Is there any sort of this GLCM codes in python? 
I've tried to develop one, but it seems it needs something to correct.

Cheers,
Hendra

**Comment by ailich** [comment]
I don't really work in python so I'm not too aware of what's out there but from some quick googling here are some resources.

https://towardsdatascience.com/glcms-a-great-tool-for-your-ml-arsenal-7a59f1e45b65
https://github.com/MartimChaves/glcm_sat_img
https://scikit-image.org/docs/stable/auto_examples/features_detection/plot_glcm.html
https://github.com/tzm030329/GLCM

**Comment by ailich** [comment]
You can also pass objects between R and python using the reticulate package in R or the rpy2 package in python if you'd like to use `GLCMTextures` but mainly work in python. Also if you want to code it yourself in python you can follow the ReadMe for this repository as well as the texture [tutorial](https://prism.ucalgary.ca/bitstream/handle/1880/51900/texture%20tutorial%20v%203_0%20180206.pdf) by Mryka Hall-Beyer

**Comment by henzb72** [comment]
Well noted.
Thank you
